### ISSUE TITLE
Razor within extension does not resolve extension assembly

### ISSUE THREAD

**Issue by sami016** [ExtCore/ExtCore#154]
Using ExtCore.WebApplication and ExtCore.Mvc 4.0.0, I'm creating an extension to serve an MVC page, with a custom model type that is defined within the extension (both the view and model are in the same dll).

MyModel.cs

`
public class MyModel
{
    public IEnumerable<string> Items { get; set; }
}
`

Everything works fine until I reference the model type in one of the extension's views.

View.cshtml:

`
@model My.Namespace.Extension.MyModel
`

Reported error:

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

The type or namespace name 'Extension' does not exist in the namespace 'My.Namespace' (are you missing an assembly reference?)

It seems that whilst ExtCore is correctly loading the extension dll and allowing controllers to be hit, the Razor engine is not aware of it. 

Extension is in a completely different folder to the main application (includeSubpaths has no efffect).

**Comment by sami016** [comment]
This issue can easily be recreated using the MVC sample by adding a custom model to the extension assembly and referencing it with the view.

> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
wlc4go2y.40d(18,90): error CS0246: The type or namespace name 'Extension' could not be found (are you missing a using directive or an assembly reference?)
wlc4go2y.40d(50,71): error CS0246: The type or namespace name 'Extension' could not be found (are you missing a using directive or an assembly reference?)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by sami016** [comment]
So I've managed to work around this by implementing an IAddMvcAction within the application.


        public void Execute(IMvcBuilder mvcBuilder, IServiceProvider serviceProvider)
        {
            mvcBuilder.AddRazorOptions(x =>
            {
                foreach (Assembly assembly in ExtensionManager.Assemblies)
                {
                    x.AdditionalCompilationReferences.Add(
                        MetadataReference.CreateFromFile(assembly.Location)
                    );
                });
            }
        }

This probably isn't worth correcting within ExtCore, since the API used above is deprecated in aspnet core 3.0 (https://aka.ms/AA1x4gg) but the work around I described should be helpful to anyone using 2.2 like I am.

**Comment by DmitrySikorsky** [comment]
Thanks for sharing the information!
