### ISSUE TITLE
Extensions work in IDE, but Razor cannot find compilation library at runtime

### ISSUE THREAD

**Issue by sami016** [ExtCore/ExtCore#155]
So, I'm trying to get a web application up and running with extensions. I'm using the mvc sample project for this. Everything runs fine with the IDE, but when I publish the projects ready for deployment, I'm seeing issues with razor compilation.

How I'm publishing:

```
dotnet publish src/WebApplication/WebApplication.csproj -c release --output .\test\
dotnet publish src/Extension/Extension.csproj -c release --output .\test\Modules\Example\
```

How I'm running:

```
cd test && dotnet WebApplication.dll
```

What I'm seeing when trying to access the extension page (500 error caused by this exception):

```
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.NETCore.App'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Does anyone have any ideas? This is off of the sample project, so I'd assumed the project versions would be configured correctly.

**Comment by DmitrySikorsky** [comment]
Hi, yes, it was discussed in https://gitter.im/ExtCore/ExtCore and here: https://github.com/ExtCore/ExtCore-Sample-Mvc/issues/3

**Comment by sami016** [comment]
Thanks for your response. I'm able to get the app running using the steps described in the post you mentioned, however, it requires me to put all dlls into the application root directory. This is problematic, as it violates the clean separation of module dependencies, which will likely cause problems down the line.

**Comment by Xarkam** [comment]
Hello, I can compile and run example app in released mode and I have extension separated.

But, I still have a problem:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLL9CSEOEUG0", Request id "0HLL9CSEOEUG0:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
bunozpfq.414(4,55): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(5,62): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(4,82): error CS0518: Predefined type 'System.Type' is not defined or imported
bunozpfq.414(4,123): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(4,140): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(4,12): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(5,81): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(5,113): error CS0518: Predefined type 'System.Type' is not defined or imported
bunozpfq.414(5,11): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(16,49): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(17,49): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(16,78): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(16,87): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(16,132): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(16,6): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(17,78): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(17,87): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(17,132): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(17,6): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(18,90): error CS0518: Predefined type 'System.Boolean' is not defined or imported
bunozpfq.414(18,41): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(21,67): error CS1983: The return type of an async method must be void, Task or Task<T>
bunozpfq.414(21,62): error CS1069: The type name 'Task' could not be found in the namespace 'System.Threading.Tasks'. This type has been forwarded to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' Consider adding a reference to that assembly.
bunozpfq.414(32,118): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(34,71): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(36,87): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(38,83): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(40,71): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(40,71): error CS0518: Predefined type 'System.Object' is not defined or imported
bunozpfq.414(40,71): error CS0518: Predefined type 'System.Boolean' is not defined or imported
bunozpfq.414(40,92): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(21,67): error CS0508: '_Views_Default_Index.ExecuteAsync()': return type must be 'Task' to match overridden member 'RazorPageBase.ExecuteAsync()'
bunozpfq.414(21,67): error CS0012: The type 'Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(31,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(31,10): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(33,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(33,10): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(35,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(35,10): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(37,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(37,10): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(39,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(39,10): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(23,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(23,13): error CS0518: Predefined type 'System.Object' is not defined or imported
bunozpfq.414(23,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
bunozpfq.414(23,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
bunozpfq.414(23,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
bunozpfq.414(23,13): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(24,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(24,13): error CS0518: Predefined type 'System.Object' is not defined or imported
bunozpfq.414(24,26): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(24,13): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(25,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(25,13): error CS0518: Predefined type 'System.Object' is not defined or imported
bunozpfq.414(25,13): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(26,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(26,13): error CS0518: Predefined type 'System.Object' is not defined or imported
bunozpfq.414(26,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
bunozpfq.414(26,31): error CS0518: Predefined type 'System.Int32' is not defined or imported
bunozpfq.414(26,35): error CS0518: Predefined type 'System.Boolean' is not defined or imported
bunozpfq.414(26,13): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(27,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(27,13): error CS0518: Predefined type 'System.Object' is not defined or imported
bunozpfq.414(27,26): error CS0518: Predefined type 'System.String' is not defined or imported
bunozpfq.414(27,13): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(28,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
bunozpfq.414(28,13): error CS0518: Predefined type 'System.Object' is not defined or imported
bunozpfq.414(28,13): error CS0518: Predefined type 'System.Void' is not defined or imported
bunozpfq.414(21,67): error CS0161: '_Views_Default_Index.ExecuteAsync()': not all code paths return a value
bunozpfq.414(18,18): error CS0518: Predefined type 'System.Void' is not defined or imported
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
I used this documentation page https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli for make my tests under linux.

**Comment by DmitrySikorsky** [comment]
This issue is related to the new assembly loading mechanism (Microsoft.NETCore.App). As workaround, just add dependencies on concrete packages, not at the top level Microsoft.NETCore.App one. I think ExtCore's assembly loading part will be totally changed in the .NET Core 3.
