### ISSUE TITLE
"Error loading assembly" warnings at launch time

### ISSUE THREAD

**Issue by HiwackVDP** [ExtCore/ExtCore#165]
Hi,

I have an application running on .net core 2.2 using ExtCore.WebApplication 4.1.
I am able to use my extensions via ExtCore, everything works perfectly.
BUT every time I launch my app, when, in "ConfigureServices", I inject ExtCore service with `services.AddExtCore(extensionsPath);`, I receive warning logs about ExtCore not being able to find assemblies. These assemblies are not my extensions, but mostly look like dependencies of my extensions, and dependencies of these dependencies.
This is an issue as I am entering a test phase where I need clear logs to know how my application is doing on a pre-production environment.

I already read [this issue](https://github.com/ExtCore/ExtCore/issues/87) and it didn't fix my problem.

Here are the warning logs :
`2019-07-25 15:27:48.852 +02:00 [WRN] Error loading assembly 'Markdig.Signed' 2019-07-25 15:27:48.899 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Markdig.Signed, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. File name: 'Markdig.Signed, Culture=neutral, PublicKeyToken=null' at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder) at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder) at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName) at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List1 assemblies)

2019-07-25 15:27:48.916 +02:00 [WRN] Error loading assembly 'Portable.BouncyCastle'
2019-07-25 15:27:48.916 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Portable.BouncyCastle, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Portable.BouncyCastle, Culture=neutral, PublicKeyToken=null'
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)

2019-07-25 15:27:48.918 +02:00 [WRN] Error loading assembly 'Rsk.IdentityServer4.Saml'
2019-07-25 15:27:48.918 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Rsk.IdentityServer4.Saml, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Rsk.IdentityServer4.Saml, Culture=neutral, PublicKeyToken=null'
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)

2019-07-25 15:27:48.920 +02:00 [WRN] Error loading assembly 'Rsk.IdentityServer4.Saml.EntityFramework'
2019-07-25 15:27:48.920 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Rsk.IdentityServer4.Saml.EntityFramework, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Rsk.IdentityServer4.Saml.EntityFramework, Culture=neutral, PublicKeyToken=null'
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List1 assemblies) `

Thanks in advance

**Comment by DmitrySikorsky** [comment]
Hi @HiwackVDP, thank you for the question. I don't think it is important, because these assemblies doesn't need to be included into the ExtCore assemblies discovery mechanism. You can just ignore that warnings.

**Comment by HiwackVDP** [comment]
Hi @DmitrySikorsky.
Thanks for the answer. I understand that these logs are not as imortant as I thought.
They actually are a real mess to read my logs so I'll just try to find a way to ignore ExtCore warnings then.
