### ISSUE TITLE
ihave a problem implementing the application context with identity and migrations

### ISSUE THREAD

**Issue by angaratosurion** [ExtCore/ExtCore#186]
ihave a problem implementing the application context with identity and migrations,
When i implement it the way it shows in the samples  it shows these error
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0311	The type 'SlimeWeb.Core.Data.SlimeDbContext' cannot be used as type parameter 'T' in the generic type or method 'DesignTimeStorageContextFactoryBase<T>'. There is no implicit reference conversion from 'SlimeWeb.Core.Data.SlimeDbContext' to 'ExtCore.Data.EntityFramework.StorageContextBase'.	SlimeWeb.Core	G:\AutoSyncWithParis-Server\My Programs\dotNet\Open Source\SlimeWeb\SlimeWeb\SlimeWeb.Core\Data\DesignTimeStorageContextFactory.cs	8	Active
`
'SlimeWeb.Core.Data.SlimeDbContext':
`   public class SlimeDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, int>, IStorageContext
    {
       
       
       
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<ApplicationUser> applicationUsers { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<Category> Catgories { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Files> Files { get; set; }
        public DbSet<FileType> FileTypes { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<GeneralSettings> Settings { get; set; }
        public GeneralSettings GeneralSettings
        {
            get
            {
                return this.Settings.FirstOrDefault();
            }
        }
        public DbSet<BannedUsers> BannedUsers { get; set; }
        public DbSet<News> News{ get; set; }

        public IStorageContext StorageContext => throw new NotImplementedException();

        public SlimeDbContext(DbContextOptions<SlimeDbContext> options)
               : base(options)
        {
           

        }

        public SlimeDbContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            string pathwithextention = System.Reflection.Assembly.GetExecutingAssembly().CodeBase;
            string path = System.IO.Path.GetDirectoryName(pathwithextention).Replace("file:\\","");
            var builder = new ConfigurationBuilder()
                            .SetBasePath(path)
                            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            var config = builder.Build();
            var directory = Path.Combine(path, "App_Data");
            if(Directory.Exists(directory)== false)
            {
                Directory.CreateDirectory(directory);
            }
            string olddbConn = config.GetValue<string>("ConnectionStrings:DefaultConnection");
            if (olddbConn != null)
            {

                string dbCon = olddbConn.Replace("|DataDirectory|", directory);
                if (dbCon != null)
                {
                    optionsBuilder.UseSqlServer(dbCon);
                    
                }
            }
               

        }

       
    }
}`

DesignTimeStorageContextFactory:
`public class DesignTimeStorageContextFactory : DesignTimeStorageContextFactoryBase<SlimeDbContext>
    { 
    }`

**Comment by postb99** [comment]
Hello, let's have a look at our project where we didn't need to use `DesignTimeStorageContextFactory`.

However, for some unit tests setup we initially used `IDesignTimeDbContextFactory` (this has been reworked since, we don't test with database setup now) and that worked.

I notice that I also had to register my DbContext this way in `Startup.cs`, this might be useful to know too.

```
// Register database-specific storage context implementation.
services_.AddScoped<IStorageContext, ApplicationStorageContext>();
```

https://github.com/SOFTINUX/Base/search?q=ApplicationStorageContext will perform lookup on master branch but currently active branch is https://github.com/SOFTINUX/Base/tree/NewPermissionsSystem-Admin

**Comment by angaratosurion** [comment]
> 
> 
> Hello, let's have a look at our project where we didn't need to use `DesignTimeStorageContextFactory`.
> 
> However, for some unit tests setup we initially used `IDesignTimeDbContextFactory` (this has been reworked since, we don't test with database setup now) and that worked.
> 
> I notice that I also had to register my DbContext this way in `Startup.cs`, this might be useful to know too.
> 
> ```
> // Register database-specific storage context implementation.
> services_.AddScoped<IStorageContext, ApplicationStorageContext>();
> ```
> 
> https://github.com/SOFTINUX/Base/search?q=ApplicationStorageContext will perform lookup on master branch but currently active branch is https://github.com/SOFTINUX/Base/tree/NewPermissionsSystem-Admin

now it  throws/shows this text in the package manager console when i go to add migrations did iforgot to add a package ?
iwant the app to use sqlserver
`ExtCore.WebApplication[0]
      Discovering and loading assemblies from DependencyContext
ExtCore.WebApplication[0]
      Assembly 'SlimeWeb, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Data, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Data.Abstractions, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Data.Entities.Abstractions, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Data.EntityFramework, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Data.Models.Abstractions, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Infrastructure, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Mvc, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.Mvc.Infrastructure, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'ExtCore.WebApplication, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'Newtonsoft.Json.Bson, Version=1.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'NuGet.Frameworks, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is discovered and loaded
ExtCore.WebApplication[0]
      Assembly 'Owin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f0ebd12fd5e55cc5' is discovered and loaded
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.native.System'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.native.System, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.native.System, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
infoverbose: System.ArgumentException: GenericArguments[0], 'Microsoft.AspNetCore.Identity.IdentityUser', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore`6[TUser,TContext,TKey,TUserClaim,TUserLogin,TUserToken]' violates the constraint of type 'TUser'.
: ExtCore.WebApplication[0]
      Executing ConfigureServices action 'ExtCore.Data.Actions.AddStorageAction'
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.native.System.Data.SqlClient.sni'
infowarn: ExtCore.WebApplication[0]
      Executing ConfigureServices action 'ExtCore.Data.EntityFramework.Actions.AddStorageContextAction'
: ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.native.System.Data.SqlClient.sni, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.native.System.Data.SqlClient.sni, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
infowarn:    An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: GenericArguments[0], 'Microsoft.AspNetCore.Identity.IdentityUser', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore`6[TUser,TContext,TKey,TUserClaim,TUserLogin,TUserToken]' violates the constraint of type 'TUser'.
: ExtCore.WebApplication[0]
      Executing ConfigureServices action 'ExtCore.Mvc.Actions.AddStaticFilesAction'
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.native.System.IO.Compression'
ExtCore.WebApplication[0]
      Executing ConfigureServices action 'ExtCore.Mvc.Actions.AddMvcAction'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.native.System.IO.Compression, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.native.System.IO.Compression, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
warnverbose: No application service provider was found.
: ExtCore.WebApplication[0]
      Error loading assembly 'runtime.native.System.Net.Http'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.native.System.Net.Http, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.native.System.Net.Http, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.native.System.Security.Cryptography.Apple'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.native.System.Security.Cryptography.Apple, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.native.System.Security.Cryptography.Apple, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl'
No DbContext named 'SlimeWebContext' was found.
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
      
      
ExtCore.WebApplication[0]
      Error loading assembly 'runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl'
ExtCore.WebApplication[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext asse`

**Comment by angaratosurion** [comment]
thanks fixed
