### ISSUE TITLE
Sqlite dll not found

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#87]
Hi Dmitry,

I worked on my extcore-mvc based application, with sqlite EF storage. However, I have a startup error:
"ExtCore.WebApplication:Warning: System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.bundle_green, Culture=neutral, PublicKeyToken=null'. Le fichier spécifié est introuvable."

I added the ExtCore.Data.EntityFramework.Sqlite as a nuGet package reference to my Security.Data.EntityFramework.Sqlite dll, then a reference to this dll to my web application.

If I didn't add this, I had no implementation found for IStorageContext.

What do I do wrong? My repository's location: https://github.com/OSAMES/Base/tree/feature/security_extension

Thank you very much for your help.

**Comment by DmitrySikorsky** [comment]
Hi!

So, answer is very easy. When you add dependency to the dll (not to the nuget package) or copy the dll into the extensions folder, you must be sure that all the packages your dll needs (have as dependencies) are either also copied into the extensions folder or included to the main web application as nuget dependencies.

**Comment by DmitrySikorsky** [comment]
It is easy to see all the dlls you need by publishing web application and looking into the folder with published app (you need to add dependencies as nuget packages before that).

**Comment by postb99** [comment]
Thank you very much for the great tip, I solved this issue by adding the nuGet package Microsoft.Data.Sqlite to my web application.
Then I had to add the IStorage service DI by uncommenting "services_.AddScoped<IStorage, Storage>()" in the "ConfigureServices(IServiceCollection services_)" of Startup class.

My controller gets called and the first query gets executed.

**Comment by DmitrySikorsky** [comment]
Happy to know that!

**Comment by NickRimmer** [comment]
I've same problems. I don't using 'SQLitePCLRaw.bundle_green' or 'SQLitePCLRaw.lib.e_sqlite3.osx' or others SQLite libs wich can't be find. I just add via nuget 'Microsoft.Data.Sqlite (2.2.0)'. And extension manager trying to load all of this libs. My application works fine, and SQLite works correct. But on start I have these warnings.

```
15:49:21.6438|WARN | ExtCore.WebApplication | System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.bundle_green, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
File name: 'SQLitePCLRaw.bundle_green, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)


15:49:21.6556|INFO | ExtCore.WebApplication | Assembly 'SQLitePCLRaw.core, Version=1.1.11.121, Culture=neutral, PublicKeyToken=1488e028ca7ab535' is discovered and loaded
15:49:21.6556|WARN | ExtCore.WebApplication | Error loading assembly 'SQLitePCLRaw.lib.e_sqlite3.linux'
15:49:21.6556|WARN | ExtCore.WebApplication | System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.lib.e_sqlite3.linux, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
File name: 'SQLitePCLRaw.lib.e_sqlite3.linux, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)


15:49:21.6556|WARN | ExtCore.WebApplication | Error loading assembly 'SQLitePCLRaw.lib.e_sqlite3.osx'
15:49:21.6556|WARN | ExtCore.WebApplication | System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.lib.e_sqlite3.osx, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
File name: 'SQLitePCLRaw.lib.e_sqlite3.osx, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)

15:49:21.6729|WARN | ExtCore.WebApplication | Error loading assembly 'SQLitePCLRaw.lib.e_sqlite3.v110_xp'
15:49:21.6729|WARN | ExtCore.WebApplication | System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.lib.e_sqlite3.v110_xp, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
File name: 'SQLitePCLRaw.lib.e_sqlite3.v110_xp, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)


15:49:21.6729|WARN | ExtCore.WebApplication | Error loading assembly 'SQLitePCLRaw.provider.e_sqlite3.netstandard11'
15:49:21.6729|WARN | ExtCore.WebApplication | System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCLRaw.provider.e_sqlite3.netstandard11, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
File name: 'SQLitePCLRaw.provider.e_sqlite3.netstandard11, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)

**Comment by HiwackVDP** [comment]
I have exactly the same problem as @NickRimmer. The assemblies I get asked for in the warnings are dependencies of packages I am using in my dlls. However, all the needed packages are included in the main application, but I still get these warnings. These aren't terminating errors, just warnings launched when injecting the ExtCore service with this line of code in ConfigureServices :
`services.AddExtCore(extensionsPath);`

See hereunder the warnings I receive :
`2019-07-25 15:27:48.852 +02:00 [WRN] Error loading assembly 'Markdig.Signed'
2019-07-25 15:27:48.899 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Markdig.Signed, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Markdig.Signed, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)


2019-07-25 15:27:48.916 +02:00 [WRN] Error loading assembly 'Portable.BouncyCastle'
2019-07-25 15:27:48.916 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Portable.BouncyCastle, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Portable.BouncyCastle, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)


2019-07-25 15:27:48.918 +02:00 [WRN] Error loading assembly 'Rsk.IdentityServer4.Saml'
2019-07-25 15:27:48.918 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Rsk.IdentityServer4.Saml, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Rsk.IdentityServer4.Saml, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)


2019-07-25 15:27:48.920 +02:00 [WRN] Error loading assembly 'Rsk.IdentityServer4.Saml.EntityFramework'
2019-07-25 15:27:48.920 +02:00 [WRN] System.IO.FileNotFoundException: Could not load file or assembly 'Rsk.IdentityServer4.Saml.EntityFramework, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Rsk.IdentityServer4.Saml.EntityFramework, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at ExtCore.WebApplication.DefaultAssemblyProvider.GetAssembliesFromDependencyContext(List`1 assemblies)
`

@DmitrySikorsky have you any idea what is going on ?
